### PR TITLE
Alpha/authentication safe submissions

### LINKED ISSUE #63: Signup Form Safe Submissions
**Description**
- Make sure signup form submissions generate no errors

**Requirements**
- [x] Do not allow form to take blank submissions
- [x] Make sure all fields only accept correct values
- [x] Give user feedback when a field is blank or filled incorrectly
- [x] Code defensively on MentorSignupServlet and MenteeSignupServlet

### PR DESCRIPTION
**Pull request by OUMontiel**
# What does this PR do?
- Adds validation to signup form

**Related Issues**
- Closes #63 

---
**Merge Checklist**
- [ ] Branch is up to date
- [ ] No code style issues

### CODE REVIEW

File: src/main/java/com/google/sps/servlets/MenteeSignupServlet.java [hunk 1]
```diff
@@ -41,17 +41,12 @@ public void doGet(HttpServletRequest request, HttpServletResponse response) thro
...
-    String user = Utility.SQL_LOCAL_USER;
-    String password = Utility.SQL_LOCAL_PASSWORD;
-
     // Set up query to retrieve all subject tags.
     String query = "SELECT * FROM Major";
 
     try {
       // Establish connection to MySQL database.
-      Connection connection = DriverManager.getConnection(url, user, password);
+      Connection connection = DriverManager.getConnection(Utility.SQL_LOCAL_URL, Utility.SQL_LOCAL_USER, Utility.SQL_LOCAL_PASSWORD);
```
Comment (abundis28) [inline src/main/java/com/google/sps/servlets/MenteeSignupServlet.java:49]: Probably wrapping this line will improve the readability.

Comment (OUMontiel) [reply src/main/java/com/google/sps/servlets/MenteeSignupServlet.java]: Hadn't noticed it was above the 100-column limit. Done!

File: src/main/webapp/script.js [hunk 2]
```diff
@@ -246,3 +243,22 @@ function fetchMentorExperience() {
     $('.selectpicker').selectpicker('refresh');
   })
 }
+
+// Example starter JavaScript for disabling form submissions if there are invalid fields
```
Comment (timothy-parsons) [inline src/main/webapp/script.js:247]: Get rid of this comment?

File: src/main/java/com/google/sps/servlets/MentorSignupServlet.java [hunk 3]
```diff
@@ -82,13 +83,15 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
     String lastName = request.getParameter("last-name");
     String username = request.getParameter("username");
     String email = userService.getCurrentUser().getEmail();
-    int major = Integer.parseInt(request.getParameter("major"));
+    int major = Utility.tryParseInt(request.getParameter("major"));
```
Comment (timothy-parsons) [inline src/main/java/com/google/sps/servlets/MentorSignupServlet.java:86]: optional - make the parameter strings constants too, so this would be 'request.getParameter(SqlConstants.USER_MAJOR_INDEX)' or something like that. Will make it harder to spell something wrong and create a bug :)

File: src/main/webapp/signup.html [hunk 4]
```diff
@@ -54,61 +54,77 @@ <h2 class="signup-subtitle text-muted">Fill in the information to complete your
...
+                  <div class="invalid-feedback">Please provide your last name (letters and spaces only).</div>
                 </div>
               </div>
               <!-- Username -->
               <div class="form-group">
                 <label for="mentee-username">Username</label>
-                <input name="username" id="mentee-username" class="form-control" placeholder="Enter username"> 
+                <input type="text" name="username" id="mentee-username" class="form-control" placeholder="Enter username" pattern="[a-zA-Z0-9_-]*" required>
+                <div class="valid-feedback">Looks good!</div>
+                <div class="invalid-feedback">Please provide a unique username (letters, numbers, hyphens, or underscores only).</div>
```
Comment (timothy-parsons) [inline src/main/webapp/signup.html:120]: Do you enforce unique usernames? If not, might be worth removing the 'unique' part of this sentence to avoid misunderstanding from the user's side.

File: src/main/webapp/script.js (hunk 2 above)
Comment (OUMontiel) [reply src/main/webapp/script.js:247]: Done!

File: src/main/webapp/signup.html (hunk 4 above)
Comment (OUMontiel) [reply src/main/webapp/signup.html:120]: Added the TODO 👍 (there is another issue already written for that).

File: src/main/java/com/google/sps/servlets/MentorSignupServlet.java (hunk 3 above)
Comment (OUMontiel) [reply src/main/java/com/google/sps/servlets/MentorSignupServlet.java:86]: Added them! Also added SQL constants for every time I query the database.

**Comment by OUMontiel** [comment]
> How exactly does the validation work at the moment? I can't figure it out - is it just checking whether required fields are filled? Where is the code for checking a unique username, for instance?
> 
> Super glad you're doing this, input validation is important!

In frontend, I check with Bootstrap whether all fields are filled out and meet required values (for example, no spaces or special characters for username, no special characters in first and last name,...).

In backend, I make sure to catch exceptions and keep default values in these cases. This is in the case of parseInt() and also when receiving a null String array in the MentorSignupServlet.

File: src/main/java/com/google/sps/classes/SqlConstants.java [hunk 5]
```diff
@@ -36,4 +36,26 @@
   public static final int QUESTION_FETCH_MAXID_COLUMN = 1;
   public static final int FOLLOWER_INSERT_QUESTIONID_COLUMN = 1;
   public static final int FOLLOWER_INSERT_ASKERID_COLUMN = 2;
+
+  // Constants to get user ID.
+  public static final int GET_USER_ID_EMAIL = 1;
+  
+  // Constants to add new user.
+  public static final int ADD_NEW_USER_FIRST_NAME = 1;
```
Comment (timothy-parsons) [inline src/main/java/com/google/sps/classes/SqlConstants.java:44]: Curious - these ints can be used on retrieval too, right? They're used in your PR for adding to the database, but maybe these names are a bit misleading if they can also be used to retrieve. Might be worth being consistent with the constants above (FOLLOWER_INSERT_ASKERID_COLUMN, for instance)

**Comment by timothy-parsons** [comment]
> > How exactly does the validation work at the moment? I can't figure it out - is it just checking whether required fields are filled? Where is the code for checking a unique username, for instance?
> > Super glad you're doing this, input validation is important!
> 
> In frontend, I check with Bootstrap whether all fields are filled out and meet required values (for example, no spaces or special characters for username, no special characters in first and last name,...).
> 
> In backend, I make sure to catch exceptions and keep default values in these cases. This is in the case of parseInt() and also when receiving a null String array in the MentorSignupServlet.

Do I understand correctly then that when you get invalid data (like in tryParseInt), you don't give the user feedback, and instead propagate a default value to the database? If that's what is happening, make sure that's updated (and perhaps leave a TODO to propagate this error instead back to the user as feedback).

File: src/main/java/com/google/sps/classes/SqlConstants.java (hunk 5 above)
Comment (OUMontiel) [reply src/main/java/com/google/sps/classes/SqlConstants.java]: Oh, I hadn't noticed the format of other columns, so I modified that so they are all consistent. And no, insertion and retrieval are different.

**Comment by OUMontiel** [comment]
Added the comments requested!

File: src/main/java/com/google/sps/servlets/MenteeSignupServlet.java [hunk 6]
```diff
@@ -45,11 +46,13 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
     String lastName = request.getParameter("last-name");
     String username = request.getParameter("username");
     String email = userService.getCurrentUser().getEmail();
-    int major = Integer.parseInt(request.getParameter("major"));
-    Boolean is_mentor = false;
+    int major = Utility.tryParseInt(request.getParameter("major"));
+        // Should not be possible for parseInt() to fail because form only allows integer values to
+        // be submitted.
```
Comment (timothy-parsons) [inline src/main/java/com/google/sps/servlets/MenteeSignupServlet.java:51]: Include this comment before the function call (the line above) and make sure indentation is consistent with the rest of this block.

Comment (timothy-parsons) [reply src/main/java/com/google/sps/servlets/MenteeSignupServlet.java:51]: Same in your other call site!

Comment (OUMontiel) [reply src/main/java/com/google/sps/servlets/MenteeSignupServlet.java]: Done!
